### ISSUE TITLE
Failed to install on OS X 10.10.5 with Atom 1.0.13 - 1.0.15.

### ISSUE THREAD

**Issue by malarkannaninvention** [willwhitney/hydrogen#111]
The following build error message was thrown.

```
> zmq@2.13.0 install /private/var/folders/4v/x63j8szs4ygbh5_sv3_rrpyr0000gs/T/apm-install-dir-115818-69749-12abaso/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/zmq.node

ld: warning: directory not found for option '-L/opt/local/lib'
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/zmq.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/4v/x63j8szs4ygbh5_sv3_rrpyr0000gs/T/apm-install-dir-115818-69749-12abaso/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/malar/.atom/.apm/.apmrc" "--userconfig" "/Users/malar/.atom/.apmrc" "install" "/private/var/folders/4v/x63j8szs4ygbh5_sv3_rrpyr0000gs/T/d-115818-69749-1ao0jif/package.tgz" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/4v/x63j8szs4ygbh5_sv3_rrpyr0000gs/T/apm-install-dir-115818-69749-12abaso/npm-debug.log
```

**Comment by lgeiger** [comment]
I'm getting the same build error after upgrading from atom 1.0.11 to 1.0.13 or 1.0.14.
Hydrogen worked fine under atom 1.0.11.

**Comment by willwhitney** [comment]
Looks like this was probably the Atom bug you mentioned, which is now closed. Can anyone confirm that this is resolved?

**Comment by malarkannaninvention** [comment]
I upgraded Xcode to 7.0 and it is resolved.

**Comment by trcook** [comment]
Requesting reopen: 
I am having the same described here. I installed Xcode 7 but it did not fix the issue

```{log}
> zmq@2.13.0 install /private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/apm-install-dir-115911-41649-qgmk3p/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild


/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/apm-install-dir-115911-41649-qgmk3p/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/tom/.atom/.apm/.apmrc" "--userconfig" "/Users/tom/.atom/.apmrc" "install" "/private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/d-115911-41649-155stgi/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/apm-install-dir-115911-41649-qgmk3p/npm-debug.log
```

**Comment by trcook** [comment]
Request reopen on this. I'm having the same issue described here. I installed xcode 7 but it did not help

OS X 10.10.5, xcode 7.0.1
Atom: 1.0.9

Previously installed hydrogen: 0.62

```
> zmq@2.13.0 install /private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/apm-install-dir-115911-41854-adh1uy/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/zmq.node

ld: warning: directory not found for option '-L/opt/local/lib'
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/zmq.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/apm-install-dir-115911-41854-adh1uy/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/tom/.atom/.apm/.apmrc" "--userconfig" "/Users/tom/.atom/.apmrc" "install" "/private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/d-115911-41854-h5hz2p/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/nj/vg3121g97fsd5ym8__cfhjlr0000gn/T/apm-install-dir-115911-41854-adh1uy/npm-debug.log
```

**Comment by trcook** [comment]
Holy cow, this is a pernicious bug that is not hydrogen's fault (as it would seem). I have a fix that is gross, but workable. I'm leaving it here to save others with similar issues a huge ammount of time. 

The solution comes from discussion in:  https://github.com/nodejs/node/issues/2933

It looks like it hits lots the npm ecosystem on os x if the user's xcode is not fully up to date. It looks like it can be resolved by manually linking in the library that node-gyp is struggling to find: 
```
cd /usr/local/lib sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
```

This is the hackiest of hacky ways to fix this. Since the link is only needed at build time, users can (and probably should) reverse the link after hydrogen installs by: 
```
rm /usr/local/lib/libgcc_s.10.5.dylib
```

No need to re-open this issue as previously requested as this is not a hydrogen issue.

**Comment by willwhitney** [comment]
Wow, this is sketch. Thanks for reporting back!
