### ISSUE TITLE
ruby kernel does not work for me

### ISSUE THREAD

**Issue by kaibioinfo** [willwhitney/hydrogen#49]
Hi,

while the python kernel is working now (after starting atom from command line) the ruby kernel is still not responding. When I run "Run Hydrogen" on some code snippet like
```ruby
  x = 6
  x
```
it starts computing but does not give any result. The last output from atom is
```
  [26252:0601/180536:INFO:CONSOLE(100)] "<IDS|MSG>,,{"msg_id":"41772bc9-cd43-4647-9e7a-303ef77a2589","username":"","session":0,"msg_type":"execute_request","version":"5.0"},{},{},{"code":"x=6\nx","silent":false,"store_history":true,"user_expressions":{},"allow_stdin":false}", source: /home/kaidu/.atom/packages/Hydrogen/lib/kernel.coffee (100)
```

Starting the ruby kernel from the ipython notebook (commandline) is working.

**Comment by willwhitney** [comment]
This is an issue with the Ruby kernel (https://github.com/SciRuby/iruby/issues/29) — it just needs to skip the signature check when it's given an empty signing key.

I probably won't have time to write a PR for this myself in the next couple of days (I'm coming up against a paper deadline for a conference). It looks like you can just add another clause [at this line](https://github.com/SciRuby/iruby/blob/e50bbcac44f9ab461d0b6d8e721db6d5f992192e/lib/iruby/session.rb#L79) and skip the check if the key is empty. It would be great if you or someone else would write a pull request to fix it!

**Comment by minad** [comment]
should be fixed in sciruby/iruby master. But what about implementing signatures in hydrogen?

**Comment by kaibioinfo** [comment]
I reinstalled iruby from sciruby/iruby master. But it is still not working yet. The complete shell output is

```
[32394:0602/155941:INFO:CONSOLE(97)] "Available kernels:", source: /home/kaidu/.atom/packages/Hydrogen/lib/kernel-manager.coffee (97)
[32394:0602/155941:INFO:CONSOLE(84)] "sending execute", source: /home/kaidu/.atom/packages/Hydrogen/lib/kernel.coffee (84)
[32394:0602/155941:INFO:CONSOLE(100)] "<IDS|MSG>,,{"msg_id":"69fbfbca-4bde-4d7b-aca3-65a6ad760382","username":"","session":0,"msg_type":"execute_request","version":"5.0"},{},{},{"code":"x=5\nx","silent":false,"store_history":true,"user_expressions":{},"allow_stdin":false}", source: /home/kaidu/.atom/packages/Hydrogen/lib/kernel.coffee (100)
[32394:0602/155941:INFO:CONSOLE(133)] "shell message:", source: /home/kaidu/.atom/packages/Hydrogen/lib/kernel.coffee (133)
```

**Comment by minad** [comment]
Maybe my fix wasn't correct and @willwhitney can help out when he has time. I am totally not into atom, haven't used it yet.

**Comment by willwhitney** [comment]
After installing IRuby from master I get the following error (for any code, run either in Hydrogen or the notebook). Have I just done something wrong installing?

```
NoMethodError: undefined method `local_variable_defined?' for #<Binding:0x007fd8d20bc838>
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/lib/iruby/backend.rb:9:in `eval'
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/lib/iruby/kernel.rb:87:in `execute_request'
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/lib/iruby/kernel.rb:47:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/lib/iruby/kernel.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/lib/iruby/command.rb:74:in `run_kernel'
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/lib/iruby/command.rb:33:in `run'
/Library/Ruby/Gems/2.0.0/gems/iruby-0.2.4/bin/iruby:5:in `<top (required)>'
/usr/bin/iruby:23:in `load'
/usr/bin/iruby:23:in `<main>'
```

**Comment by willwhitney** [comment]
And yeah, I do want to add signing to Hydrogen at some point. At present it only ever starts kernels on localhost and can't connect to remote kernels, so it's not critical.

**Comment by minad** [comment]
@willwhitney this means your ruby version is too old

**Comment by kaibioinfo** [comment]
It is working now if I save the file before running hydrogen!
It's a bit strange, as in the console output it seems that hydrogen is sending the expression and not the filename. However, saving the file solves the problem.

**Comment by willwhitney** [comment]
OK, glad it's working for you now!

@minad thanks for the quick fix!
